version: "3.3"

services:

  mlflow:
    image: wisrovi/wyoloservice:mlflow
    restart: always
    environment:
      # db
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice # Conexión a PostgreSQL
      # minio
      - MLFLOW_S3_ENDPOINT_URL=http://mlflow-minio:9000 # URL del servidor MinIO
      - AWS_ACCESS_KEY_ID=wisrovi # Credenciales de MinIO
      - AWS_SECRET_ACCESS_KEY=wyoloservice # Credenciales de MinIO
      #mlflow
      - MLFLOW_TRACKING_URI=http://mlflow:5000 # URI de seguimiento de MLflow
      - MLFLOW_ARTIFACT_URI=s3://mlflow-artifacts/ # Bucket en MinIO donde se almacenarán los artefactos
    command: [ "mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "postgresql+psycopg2://postgres:postgres@postgres:5432/wyoloservice", "--default-artifact-root", "s3://mlflow-artifacts/" ]
    ports:
      - "23435:5000"
    networks:
      - train_service

  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wyoloservice
      - CONTROL_HOST=192.168.1.137
      - CIFS_USER=wisrovi
      - CIFS_PASS=wyoloservice
    volumes:
      - ./wyoloservice_data/postgres:/var/lib/postgresql/data
    ports:
      - "23436:5432"
    restart: always
    networks:
      - train_service

  redis:
    image: redis:7-alpine
    ports:
      - "23437:6379"
    volumes:
      - ./wyoloservice_data/cache_redis:/data
    networks:
      - train_service

  redis_commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=wisrovi
      - HTTP_PASSWORD=wyoloservice
    ports:
      - "23438:8081"
    depends_on:
      - redis
    networks:
      - train_service

  mlflow-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      - MINIO_ROOT_USER=wisrovi
      - MINIO_ROOT_PASSWORD=wyoloservice
      - CONTROL_HOST=192.168.1.137
      - CIFS_USER=wisrovi
      - CIFS_PASS=wyoloservice
    ports:
      - "23439:9000"
      - "23440:9001" # web admin
    volumes:
      - ./wyoloservice_data/mlflow_minio:/data
    networks:
      - train_service

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=${REDIS_URL:-redis://redis:6379/0}
    ports:
      - "23441:5555"
    depends_on:
      - redis
    networks:
      - train_service

  sambas:
    image: dperson/samba
    env_file:
      - /config/control_host.env
    environment:
      - TZ=Europe/Madrid # Time zone
      - USERID=1000 # User ID (customize based on your system)
      - GROUPID=1000 # Group ID (customize based on your system)
      - SAMBA_USERS=${CIFS_USER}:${CIFS_PASS}
    volumes:
      - /dataset/datasets:/data/datasets
      - /dataset/config_models:/data/config_versions
      - /dataset/db:/data/api_database
    restart: always
    command: >
      -u "${CIFS_USER};${CIFS_PASS}" 
      -s "datasets;/data/datasets;yes;no;yes;all" 
      -s "config_versions;/data/config_versions;yes;no;yes;all" 
      -s "api_database;/data/api_database;yes;no;yes;all"
    ports:
      # - "139:139"
      - "23442:445"
      # - "137:137/udp"
      # - "138:138/udp"

  optuna_official_dashboard:
    image: python:3.10-slim
    container_name: optuna_official_dashboard
    restart: always
    ports:
      - "23443:8080"
    command: >
      sh -c "apt-get update && apt-get install -y libpq-dev gcc && pip install optuna-dashboard psycopg2-binary && optuna-dashboard postgresql://postgres:postgres@192.168.10.252:23436/wyoloservice --host 0.0.0.0 --port 8080"


networks:
  train_service:
    name: train_service
    driver: bridge
