version: "3.3"
services:
  fastapi:
    build: ./control-plane/api
    image: wisrovi/train_service/api/server:v1.0.0
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    volumes:
      - ./control-plane/api:/app
    networks:
      - train_service

  gui:
    build: ./control-plane/interfaz
    image: wisrovi/train_service/interfaz/ui:v1.0.0
    ports:
      - "7860:7860"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi
    volumes:
      - ./control-plane/interfaz:/app
    networks:
      - train_service

networks:
  train_service:
    name: train_service
